### ISSUE TITLE
Movement Keys cannot be bound to a mouse button

### ISSUE THREAD

**Issue by earthcrafterman** [GentenStudios/quartz-engine#57]
The Movement buttons (moveForward, strafeLeft, etc) are of type events::Keys. Mouse buttons are of type events::MouseButton.

**Comment by apachano** [comment]
Is this limit caused by our tools or our implementation of them?

**Comment by beeperdeeper089** [comment]
This currently an issue due to our implementation of them, however, it shouldn't be too hard to do this.

**Comment by tobyplowy** [comment]
Maybe this issue needs to be renamed to something like "assign any button to any control/command"
So that you can use F3 or something to mine blocks XD
That may sound stupid but there are odd keyboards out there that would actually benefit from this kind of implementation. Just Google odd keyboards as reference :)
Anyways this is just an idea.

**Comment by beeperdeeper089** [comment]
Similar to my comment in #52
